#!/usr/bin/env sh

rm urls.txt
curl https://www.domcop.com/files/top/top10milliondomains.csv.zip -o /tmp/urls.csv.zip
7z e -so /tmp/urls.csv.zip > /tmp/urls.csv
cat /tmp/urls.csv | tail -n +2 | grep -v -e doubleclick | head -n 25000 | awk -F '","' '{print "https://"$2}' > urls.txt
rm /tmp/urls.csv*
